// src/lib/license.ts
import { jwtVerify, importJWK, type JWTPayload } from "jose";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { getConfigDir } from "./config.js";

// Embedded public key — generated by scripts/generate-license-keys.ts
const PUBLIC_JWK = {
  kty: "EC",
  x: "MFqIhLSlnxuqEWWvfUgyPM-HU9SmoW6EnL9JZvZyLwU",
  y: "eJdW1s52OIcH1t3FvENXlV_W4QvuXxSbZOKeo963u_s",
  crv: "P-256",
} as const;

const GRACE_PERIOD_DAYS = 30;

export interface LicensePayload {
  iss: string;
  sub: string;
  customer: string;
  plan: "community" | "trial" | "pro" | "enterprise";
  modules: string[];
  seats: number;
  trial: boolean;
}

export interface LicenseResult {
  isValid: boolean;
  isGracePeriod: boolean;
  daysRemaining: number;
  payload: LicensePayload | null;
  error?: string;
}

const COMMUNITY_RESULT: LicenseResult = {
  isValid: true,
  isGracePeriod: false,
  daysRemaining: Infinity,
  payload: {
    iss: "industream.com",
    sub: "community",
    customer: "Community",
    plan: "community",
    modules: [],
    seats: Infinity,
    trial: false,
  },
};

export async function validateLicense(
  token?: string,
): Promise<LicenseResult> {
  if (!token) return COMMUNITY_RESULT;

  try {
    const publicKey = await importJWK(PUBLIC_JWK, "ES256");
    // Allow tokens expired up to grace period + 1 day so we can handle grace logic ourselves
    const { payload } = await jwtVerify(token, publicKey, {
      issuer: "industream.com",
      clockTolerance: (GRACE_PERIOD_DAYS + 7) * 86400,
    });

    const licensePayload = payload as unknown as LicensePayload & JWTPayload;
    const expiration = (payload.exp ?? 0) * 1000;
    const now = Date.now();
    const daysRemaining = Math.floor((expiration - now) / 86400000);
    const gracePeriodEnd = expiration + GRACE_PERIOD_DAYS * 86400000;

    if (now > gracePeriodEnd) {
      return {
        isValid: false,
        isGracePeriod: false,
        daysRemaining,
        payload: licensePayload,
        error: `License expired ${Math.abs(daysRemaining)} days ago (grace period exceeded)`,
      };
    }

    return {
      isValid: true,
      isGracePeriod: now > expiration,
      daysRemaining,
      payload: licensePayload,
    };
  } catch (error) {
    return {
      isValid: false,
      isGracePeriod: false,
      daysRemaining: 0,
      payload: null,
      error: error instanceof Error ? error.message : "Invalid license",
    };
  }
}

export async function loadLicenseFromDisk(): Promise<string | undefined> {
  try {
    const filePath = join(getConfigDir(), "industream.license");
    return (await readFile(filePath, "utf-8")).trim();
  } catch {
    return undefined;
  }
}
